services:
  db:
    image: postgis/postgis:15-3.5  
    container_name: geochecker_postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-scmbr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-geochecker}"
      POSTGRES_DB:  "${POSTGRES_DB:-geochecker}"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-scmbr} -d ${POSTGRES_DB:-geochecker}"]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-scmbr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-geochecker}"
      POSTGRES_DB: "${POSTGRES_DB:-geochecker}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-geochecker}"
      API_KEY_SECRET: "${API_KEY_SECRET:-geochecker}"
      WEBHOOK_URL: "${WEBHOOK_URL:-}"
    volumes:
      - ./backend/.env:/app/.env
      - ./configs:/app/configs:ro
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:-geochecker}"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 5s
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-geochecker}"]
  migrate: 
    image: migrate/migrate 
    volumes:
      - ./migrations:/migrations
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-scmbr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-geochecker}"
      POSTGRES_DB: "${POSTGRES_DB:-geochecker}"
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER:-scmbr}:${POSTGRES_PASSWORD:-geochecker}@db:5432/${POSTGRES_DB:-geochecker}?sslmode=disable", "up"]
    links: 
      - db
    depends_on:
      db:
        condition: service_healthy
  
volumes:
  postgres_data:
  redis_data:
