http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
postgres:
  host: db
  port: 5432
  sslmode: disable
redis:
  host: redis
  port: 6379
  cacheTTL: 5m
  streamKey: webhook_tasks
  group: webhook_workers
  maxAttempts: 5
  deadLetterStream: dead_webhook_tasks
searchRadius: 100